2019-07-31 10:19:59,434  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:19,670  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:20,247  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:20,941  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:21,401  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:22,170  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:22,388  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:22,617  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:23,159  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
2019-07-31 10:22:23,427  WARNING  26104  C:\Users\hanna\Envs\DataManEnv\lib\site-packages\django\utils\log.py  log_response  Line 228  Not Found: /favicon.ico  
